# Generated by Django 4.1.7 on 2023-02-25 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='imagens-dos-filmes')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('ANIME', 'Anime'), ('ACAO', 'Ação'), ('FICCAO', 'Ficção'), ('TERROR', 'terror'), ('SUSPENSE', 'Suspense'), ('ROMANCE', 'Romance'), ('DRAMA', 'Drama'), ('COMEDIA', 'Comédia'), ('FAMILIA', 'Família'), ('GUERRA', 'Guerra'), ('FANTASIA', 'Fantasia')], max_length=25)),
                ('visualizações', models.IntegerField(default=0)),
                ('dataCriacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
