# Generated by Django 4.1.7 on 2023-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_filme_capafilme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='capaFilme',
            field=models.ImageField(default='0', upload_to='capa-filmes'),
        ),
    ]
