# Generated by Django 4.1.7 on 2023-03-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0004_alter_filme_capafilme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='capaFilme',
        ),
    ]
