# Generated by Django 4.1.7 on 2023-03-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0006_filme_capafilme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='visualizações',
            new_name='visualizacoes',
        ),
    ]
