# Generated by Django 4.1.7 on 2023-03-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0007_rename_visualizações_filme_visualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='duracao',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
